/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import domen.Dimenzije;
import domen.Dusek;
import domen.Materijal;
import domen.Tvrdoca;
import domen.Velicina;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logika.KontrolerK;

/**
 *
 * @author Master
 */
public class IzmenaDusekaDijalog extends javax.swing.JDialog {

    IzmenaDusekaForma forma;
    Dusek dusek;

    /**
     * Creates new form IzmenaDusekaDijalog
     */
    public IzmenaDusekaDijalog(Dusek d, IzmenaDusekaForma forma) {
        initComponents();
        this.forma = forma;
        this.dusek = d;
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtNaziv = new javax.swing.JTextField();
        txtCena = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbMaterijal = new javax.swing.JComboBox();
        cbTvrdoca = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbVelicine = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv Duseka:");

        jButton1.setText("Izmeni");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Cena:");

        jLabel3.setText("Materijal:");

        cbMaterijal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbTvrdoca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Tvrdoca:");

        jLabel5.setText("Velicina:");

        cbVelicine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbMaterijal, 0, 237, Short.MAX_VALUE)
                            .addComponent(txtCena)
                            .addComponent(txtNaziv)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTvrdoca, 0, 237, Short.MAX_VALUE)
                            .addComponent(cbVelicine, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbMaterijal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbTvrdoca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbVelicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String naziv = txtNaziv.getText();
        String cenaS = txtCena.getText();
        if (naziv == null || cenaS == null || naziv.equals("") || cenaS.equals("")) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti dusek");
            return;
        }
        double cena = Double.parseDouble(cenaS);
        Materijal m = (Materijal) cbMaterijal.getSelectedItem();
        Tvrdoca t = (Tvrdoca) cbTvrdoca.getSelectedItem();
        int id = dusek.getDusekID();
        Dusek d = new Dusek(id, naziv, cena, m.getMaterijalID(), t.getTvrdocaID());

        boolean validan = KontrolerK.getInstance().validirajIzmenuDuseka(d);
        if (!validan) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti dusek");
            return;
        }
        boolean signal = KontrolerK.getInstance().izmeniDusek(d);
        if (signal) {
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio dusek");
            txtNaziv.setText("");
            txtCena.setText("");
            sacuvajDimenzije(id);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti dusek");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(IzmenaDusekaDijalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(IzmenaDusekaDijalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(IzmenaDusekaDijalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(IzmenaDusekaDijalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                IzmenaDusekaDijalog dialog = new IzmenaDusekaDijalog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbMaterijal;
    private javax.swing.JComboBox cbTvrdoca;
    private javax.swing.JComboBox cbVelicine;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables
     private void srediFormu() {
        ArrayList<Materijal> listaMaterijala = KontrolerK.getInstance().vratiMaterijale();
        cbMaterijal.removeAllItems();
        for (Materijal materijal : listaMaterijala) {
            cbMaterijal.addItem(materijal);
        }
        cbMaterijal.setSelectedIndex(dusek.getMaterijal() - 1);
        ArrayList<Tvrdoca> listaTvrdoce = KontrolerK.getInstance().vratiTvrdoce();
        cbTvrdoca.removeAllItems();
        for (Tvrdoca tvrdoca : listaTvrdoce) {
            cbTvrdoca.addItem(tvrdoca);
        }
        cbTvrdoca.setSelectedIndex(dusek.getTvrdoca() - 1);
        ArrayList<Velicina> listaVelicina = KontrolerK.getInstance().vratiVelicine();
        cbVelicine.removeAllItems();
        for (Velicina v : listaVelicina) {
            cbVelicine.addItem(v);
        }
        txtNaziv.setText(dusek.getNazivDuseka());
        txtCena.setText(dusek.getCena() + "");
    }

    private void sacuvajDimenzije(int id) {
        Velicina v = (Velicina) cbVelicine.getSelectedItem();
        int idV = v.getVelicinaID();
        Dimenzije d = new Dimenzije(idV, id);
        KontrolerK.getInstance().izmeniDimenzije(d);
    }

}
