/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import domen.Prodavac;
import javax.swing.JOptionPane;

/**
 *
 * @author DusanIMilos
 */
public class KlijentForma extends javax.swing.JFrame {

    Prodavac p;

    /**
     * Creates new form KlijentForma
     */
    public KlijentForma(Prodavac p) {
        initComponents();
        this.p = p;
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblKorisnik = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiDodajMaterijal = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiDodajDusek = new javax.swing.JMenuItem();
        jmiObrisiDusek = new javax.swing.JMenuItem();
        jmiPretraziDusek = new javax.swing.JMenuItem();
        jmiIzmeniDusek = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiDodajPorudzbinu = new javax.swing.JMenuItem();
        jmiPretraziPorudzbinu = new javax.swing.JMenuItem();
        jmiStorniraj = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ulogovani korisnik:");

        lblKorisnik.setText(" ");

        jMenu1.setText("Materijal");

        jmiDodajMaterijal.setText("Dodaj");
        jmiDodajMaterijal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDodajMaterijalActionPerformed(evt);
            }
        });
        jMenu1.add(jmiDodajMaterijal);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Dusek");

        jmiDodajDusek.setText("Dodaj");
        jmiDodajDusek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDodajDusekActionPerformed(evt);
            }
        });
        jMenu2.add(jmiDodajDusek);

        jmiObrisiDusek.setText("Obrisi");
        jmiObrisiDusek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiObrisiDusekActionPerformed(evt);
            }
        });
        jMenu2.add(jmiObrisiDusek);

        jmiPretraziDusek.setText("Pretrazi");
        jmiPretraziDusek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretraziDusekActionPerformed(evt);
            }
        });
        jMenu2.add(jmiPretraziDusek);

        jmiIzmeniDusek.setText("Izmeni");
        jmiIzmeniDusek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIzmeniDusekActionPerformed(evt);
            }
        });
        jMenu2.add(jmiIzmeniDusek);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Porudzbina");

        jmiDodajPorudzbinu.setText("Dodaj");
        jmiDodajPorudzbinu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDodajPorudzbinuActionPerformed(evt);
            }
        });
        jMenu3.add(jmiDodajPorudzbinu);

        jmiPretraziPorudzbinu.setText("Pretrazi");
        jmiPretraziPorudzbinu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretraziPorudzbinuActionPerformed(evt);
            }
        });
        jMenu3.add(jmiPretraziPorudzbinu);

        jmiStorniraj.setText("Storniraj");
        jmiStorniraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiStornirajActionPerformed(evt);
            }
        });
        jMenu3.add(jmiStorniraj);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(lblKorisnik)
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblKorisnik))
                .addContainerGap(310, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiDodajPorudzbinuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDodajPorudzbinuActionPerformed
        try {
            JOptionPane.showMessageDialog(this, "Sistem je kreirao porudzbinu");
            new DodavanjePorudzbinaForma(this).setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da kreira porudzbinu");
        }

    }//GEN-LAST:event_jmiDodajPorudzbinuActionPerformed

    private void jmiDodajMaterijalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDodajMaterijalActionPerformed
        try {
            JOptionPane.showMessageDialog(this, "Sistem je kreirao materijal");
            new DodavanjeMaterijalaForm(this).setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da kreira materijal");
        }

    }//GEN-LAST:event_jmiDodajMaterijalActionPerformed

    private void jmiDodajDusekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDodajDusekActionPerformed
        try {
            JOptionPane.showMessageDialog(this, "Sistem je kreirao dusek");
            new DodavanjeDusekaForm(this).setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da kreira dusek");
        }

    }//GEN-LAST:event_jmiDodajDusekActionPerformed

    private void jmiPretraziDusekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretraziDusekActionPerformed
        new PretrazivanjeDusekaForma(this).setVisible(true);
    }//GEN-LAST:event_jmiPretraziDusekActionPerformed

    private void jmiObrisiDusekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiObrisiDusekActionPerformed
        new BrisanjeDusekaForma(this).setVisible(true);
    }//GEN-LAST:event_jmiObrisiDusekActionPerformed

    private void jmiIzmeniDusekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIzmeniDusekActionPerformed
        new IzmenaDusekaForma(this).setVisible(true);
    }//GEN-LAST:event_jmiIzmeniDusekActionPerformed

    private void jmiPretraziPorudzbinuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretraziPorudzbinuActionPerformed
        new PretrazivanjePorudzbinaForma(this).setVisible(true);
    }//GEN-LAST:event_jmiPretraziPorudzbinuActionPerformed

    private void jmiStornirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiStornirajActionPerformed
        new StorniranjePorudzbineForma(this).setVisible(true);
    }//GEN-LAST:event_jmiStornirajActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(KlijentForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(KlijentForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(KlijentForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(KlijentForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new KlijentForma().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiDodajDusek;
    private javax.swing.JMenuItem jmiDodajMaterijal;
    private javax.swing.JMenuItem jmiDodajPorudzbinu;
    private javax.swing.JMenuItem jmiIzmeniDusek;
    private javax.swing.JMenuItem jmiObrisiDusek;
    private javax.swing.JMenuItem jmiPretraziDusek;
    private javax.swing.JMenuItem jmiPretraziPorudzbinu;
    private javax.swing.JMenuItem jmiStorniraj;
    private javax.swing.JLabel lblKorisnik;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        lblKorisnik.setText(p.toString());
    }

}
